service: myfirstserverlessproject

frameworkVersion: '2'

plugins:
  - serverless-offline
  - serverless-plugin-typescript
  - serverless-dotenv-plugin

custom:
  dotenv:
    path: ./.env
    basePath: ./

provider:
  name: aws
  runtime: nodejs12.x
  timeout: 10
  region: us-east-1
  environment:
    AUTH0_CLIENT_ID: ${file(./secrets.json):AUTH0_CLIENT_ID}
    AUTH0_CLIENT_PUBLIC_KEY: ${file(./public_key)}

functions:
  auth:
    handler: handler.auth
  hello:
    handler: handler.hello
    events:
      - http:
          path: 'hello'
          method: get
          cors: true
  create:
    handler: handler.create
    events:
      -
        http:
          path: 'notes'
          method: post
          cors: true
  getOne:
    handler: handler.getOne
    events:
      -
        http:
          path: 'notes/{id}'
          method: get
  getAll:
    handler: handler.getAll
    events:
      -
        http:
          path: 'notes'
          method: get
          authorizer: auth
          cors: true
  update:
    handler: handler.update
    events:
      -
        http:
          path: 'notes/{id}'
          method: put
          cors: true
  delete:
    handler: handler.deleteOne
    events:
      -
        http:
          path: 'notes/{id}'
          method: delete
          cors: true

resources:
  Resources:
    # This response is needed for custom authorizer failures cors support ¯\_(ツ)_/¯
    GatewayResponse:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: EXPIRED_TOKEN
        RestApiId:
          Ref: 'ApiGatewayRestApi'
        StatusCode: '401'
    AuthFailureGatewayResponse:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: UNAUTHORIZED
        RestApiId:
          Ref: 'ApiGatewayRestApi'
        StatusCode: '401'
