name: Deploy main branch

on:
  push:
    branches:
      - 'main'
  pull_request:
    types: [ opened, closed, synchronize, reopened ]

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'skip_ci') }} || github.event.pull_request.draft == false
    strategy:
      matrix:
        node-version: [ 12.x ]
    steps:
      - uses: actions/checkout@v2

      - name: Use NodeJS ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Create env file
        run: |
          cat > .env << EOF
          ${{ secrets.DB_ENV }}
          EOF

      - name: Create Auth0 secrets
        run: |
          cat > secrets.json << EOF
          {
            "AUTH0_CLIENT_ID": ${{ secrets.AUTH0_CLIENT_ID }}
          }
          EOF

      - run: yarn install --frozen-lockfile

      - name: Serverless deploy
        uses: serverless/github-action@master
        with:
          args: deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
